name: CI/CD Deploy on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code on GitHub runner (just to use ssh)
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ SSH into VPS and deploy
    - name: Build & Deploy on VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # go to parent folder where we keep deployment
          mkdir -p ${{ secrets.VPS_PATH }}
          cd ${{ secrets.VPS_PATH }}
          
          # check if folder is a git repo
          if [ -d ".git" ]; then
            echo "Repo exists, pulling latest code..."
            git reset --hard
            git pull origin main
          else
            echo "Repo does not exist, cloning..."
            git clone git@github.com:abdollahimostafa/BaleDdockerized.git .
          fi

          # rebuild containers using Docker Compose
          docker compose up -d --build

          # show running containers for verification
          docker compose ps
